/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WithdrawRouteImport } from "./routes/withdraw";
import { Route as WatchRouteImport } from "./routes/watch";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as OffersRouteImport } from "./routes/offers";
import { Route as ReferralsRouteImport } from "./routes/referrals";
import { Route as PtcRouteImport } from "./routes/ptc";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";

const WithdrawRoute = WithdrawRouteImport.update({
  id: "/withdraw",
  path: "/withdraw",
  getParentRoute: () => rootRouteImport,
});
const WatchRoute = WatchRouteImport.update({
  id: "/watch",
  path: "/watch",
  getParentRoute: () => rootRouteImport,
});
const OffersRoute = OffersRouteImport.update({
  id: "/offers",
  path: "/offers",
  getParentRoute: () => rootRouteImport,
});
const ReferralsRoute = ReferralsRouteImport.update({
  id: "/referrals",
  path: "/referrals",
  getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
});
const PtcRoute = PtcRouteImport.update({
  id: "/ptc",
  path: "/ptc",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PtcRoute: PtcRoute,
  OffersRoute: OffersRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  WatchRoute: WatchRoute,
  WithdrawRoute: WithdrawRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
